    dw __graphic00
    dw __graphic01
    dw __graphic02
    dw __graphic03
    dw __graphic04
    dw __graphic05
    dw __graphic06
    dw __graphic07
    dw __graphic08
    dw __graphic09
    dw __graphic10
    dw __graphic11
    dw __graphic12
    dw __graphic13
    dw __graphic14
    dw __graphic15
;        ..X XXX 
;        .. X X  
;        ..X XXX 
;        ..X     
;        ..X XXXX
;        ..X XXXX
;        ...X XXX
;        ...XX   
;        ..X     
;        .X X    
;        X XX    
;        X XXX   
;        X XXXX  
;        X XXXXX 
;        .X  XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ...X    
;        ....XXXX
__graphic00:
    db 03bh
    db 0c0h
    db 011h
    db 0c0h
    db 02bh
    db 0c0h
    db 011h
    db 0c0h
    db 01fh
    db 0c0h
    db 010h
    db 0c0h
    db 010h
    db 0e0h
    db 008h
    db 0e0h
    db 007h
    db 0c0h
    db 01fh
    db 080h
    db 02fh
    db 000h
    db 04fh
    db 000h
    db 047h
    db 000h
    db 043h
    db 000h
    db 041h
    db 080h
    db 030h
    db 0c0h
    db 010h
    db 0c0h
    db 010h
    db 0c0h
    db 010h
    db 0c0h
    db 010h
    db 0c0h
    db 010h
    db 0c0h
    db 010h
    db 0c0h
    db 010h
    db 0e0h
    db 00fh
    db 0f0h
    db 000h
    db 0ffh
__graphic01:
    db 03ch
    db 003h
    db 088h
    db 003h
    db 0d4h
    db 003h
    db 088h
    db 003h
    db 0f8h
    db 003h
    db 008h
    db 003h
    db 008h
    db 007h
    db 010h
    db 007h
    db 0e0h
    db 003h
    db 0f8h
    db 001h
    db 0f4h
    db 000h
    db 0f2h
    db 000h
    db 0e2h
    db 000h
    db 0c2h
    db 000h
    db 082h
    db 001h
    db 00ch
    db 003h
    db 008h
    db 003h
    db 008h
    db 003h
    db 008h
    db 003h
    db 008h
    db 003h
    db 008h
    db 003h
    db 008h
    db 003h
    db 008h
    db 007h
    db 0f0h
    db 00fh
    db 000h
    db 0ffh
;        ....X..X
;        ...X XX 
;        ....    
;        .... XXX
;        ....X XX
;        ....XX  
;        ..XX    
;        ..X X   
;        .. XXX  
;        .. XXXX 
;        ..X  XXX
;        ...X XXX
;        ...X XXX
;        ...X XXX
;        ...X XXX
;        ...X XXX
;        ....X   
;        .....XXX
__graphic02:
    db 04bh
    db 0f6h
    db 000h
    db 0e0h
    db 009h
    db 0f0h
    db 00fh
    db 0f0h
    db 008h
    db 0f0h
    db 004h
    db 0f0h
    db 003h
    db 0c0h
    db 00fh
    db 0c0h
    db 017h
    db 0c0h
    db 023h
    db 0c0h
    db 021h
    db 0c0h
    db 018h
    db 0e0h
    db 008h
    db 0e0h
    db 008h
    db 0e0h
    db 008h
    db 0e0h
    db 008h
    db 0e0h
    db 008h
    db 0f0h
    db 007h
    db 0f8h
    db 000h
    db 0ffh
__graphic03:
    db 04ch
    db 06fh
    db 000h
    db 007h
    db 090h
    db 00fh
    db 0f0h
    db 00fh
    db 010h
    db 00fh
    db 020h
    db 00fh
    db 0c0h
    db 003h
    db 0f0h
    db 003h
    db 0e8h
    db 003h
    db 0c4h
    db 003h
    db 084h
    db 003h
    db 018h
    db 007h
    db 010h
    db 007h
    db 010h
    db 007h
    db 010h
    db 007h
    db 010h
    db 007h
    db 010h
    db 00fh
    db 0e0h
    db 01fh
    db 000h
    db 0ffh
;        ...X XX 
;        ...X    
;        ...X XXX
;        ....X XX
;        ...X    
;        ..X XX  
;        ..X XXX 
;        ..X  XXX
;        ...X XXX
;        ...X XXX
;        ...X XXX
;        ...X XXX
;        ....X   
;        .....XXX
__graphic04:
    db 053h
    db 0e0h
    db 009h
    db 0e0h
    db 00fh
    db 0e0h
    db 008h
    db 0f0h
    db 004h
    db 0e0h
    db 00fh
    db 0c0h
    db 013h
    db 0c0h
    db 011h
    db 0c0h
    db 018h
    db 0e0h
    db 008h
    db 0e0h
    db 008h
    db 0e0h
    db 008h
    db 0e0h
    db 008h
    db 0f0h
    db 007h
    db 0f8h
    db 000h
    db 0ffh
__graphic05:
    db 054h
    db 007h
    db 090h
    db 007h
    db 0f0h
    db 007h
    db 010h
    db 00fh
    db 020h
    db 007h
    db 0f0h
    db 003h
    db 0c8h
    db 003h
    db 088h
    db 003h
    db 018h
    db 007h
    db 010h
    db 007h
    db 010h
    db 007h
    db 010h
    db 007h
    db 010h
    db 00fh
    db 0e0h
    db 01fh
    db 000h
    db 0ffh
;        ....X X 
;        ....X   
;        ....X XX
;        .....X X
;        .....X  
;        ....X X 
;        ....X XX
;        ....X XX
;        .....X  
;        ......XX
__graphic06:
    db 05bh
    db 0f0h
    db 005h
    db 0f0h
    db 007h
    db 0f0h
    db 004h
    db 0f8h
    db 002h
    db 0f8h
    db 003h
    db 0f0h
    db 005h
    db 0f0h
    db 004h
    db 0f0h
    db 004h
    db 0f8h
    db 003h
    db 0fch
    db 000h
    db 0ffh
__graphic07:
    db 05ch
    db 00fh
    db 0a0h
    db 00fh
    db 0e0h
    db 00fh
    db 020h
    db 01fh
    db 040h
    db 01fh
    db 0c0h
    db 00fh
    db 0a0h
    db 00fh
    db 020h
    db 00fh
    db 020h
    db 01fh
    db 0c0h
    db 03fh
    db 000h
    db 0ffh
;        ....XXX.
;        ...X   X
;        ..X     
;        ..X     
;        ..X     
;        ...X    
;        ....X   
;        .....X  
;        ......X 
;        .......X
__graphic08:
    db 00eh
    db 0f1h
    db 000h
    db 0e0h
    db 00eh
    db 0c0h
    db 01fh
    db 0c0h
    db 01fh
    db 0c0h
    db 01fh
    db 0e0h
    db 00fh
    db 0f0h
    db 007h
    db 0f8h
    db 003h
    db 0fch
    db 001h
    db 0feh
    db 000h
    db 0ffh
__graphic09:
    db 00fh
    db 08fh
    db 000h
    db 007h
    db 070h
    db 003h
    db 0f8h
    db 003h
    db 0f8h
    db 003h
    db 0f8h
    db 007h
    db 0f0h
    db 00fh
    db 0e0h
    db 01fh
    db 0c0h
    db 03fh
    db 080h
    db 07fh
    db 000h
    db 0ffh
;        .....XX.
;        ....X  X
;        ...X    
;        ...X    
;        ....X   
;        .....X  
;        ......X 
;        .......X
__graphic10:
    db 00eh
    db 0f9h
    db 000h
    db 0f0h
    db 006h
    db 0e0h
    db 00fh
    db 0e0h
    db 00fh
    db 0f0h
    db 007h
    db 0f8h
    db 003h
    db 0fch
    db 001h
    db 0feh
    db 000h
    db 0ffh
__graphic11:
    db 00fh
    db 09fh
    db 000h
    db 00fh
    db 060h
    db 007h
    db 0f0h
    db 007h
    db 0f0h
    db 00fh
    db 0e0h
    db 01fh
    db 0c0h
    db 03fh
    db 080h
    db 07fh
    db 000h
    db 0ffh
;        .....X X
;        ....X   
;        ....X   
;        .....X  
;        ......X 
;        .......X
__graphic12:
    db 00eh
    db 0f8h
    db 002h
    db 0f0h
    db 007h
    db 0f0h
    db 007h
    db 0f8h
    db 003h
    db 0fch
    db 001h
    db 0feh
    db 000h
    db 0ffh
__graphic13:
    db 00fh
    db 01fh
    db 040h
    db 00fh
    db 0e0h
    db 00fh
    db 0e0h
    db 01fh
    db 0c0h
    db 03fh
    db 080h
    db 07fh
    db 000h
    db 0ffh
;        ......X.
;        .....X X
;        ......X 
;        .......X
__graphic14:
    db 00eh
    db 0fdh
    db 000h
    db 0f8h
    db 002h
    db 0fch
    db 001h
    db 0feh
    db 000h
    db 0ffh
__graphic15:
    db 00fh
    db 0bfh
    db 000h
    db 01fh
    db 040h
    db 03fh
    db 080h
    db 07fh
    db 000h
    db 0ffh
; 408
