    dw __graphic00
    dw __graphic01
    dw __graphic02
    dw __graphic03
    dw __graphic04
    dw __graphic05
    dw __graphic06
    dw __graphic07
    dw __graphic08
    dw __graphic09
    dw __graphic10
    dw __graphic11
    dw __graphic12
    dw __graphic13
    dw __graphic14
    dw __graphic15
;        ...X...X
;        ..XXX.XX
;        ..XXXXXX
;        ...     
;        ... XXXX
;        ... XXXX
;        ...X XXX
;        ...XX   
;        ..X     
;        .X X    
;        X XX    
;        X XXX   
;        X XXXX  
;        X XXXXX 
;        .X  XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ..X XXXX
;        ...X    
;        ....XXXX
__graphic00:
    db 01ch
    db 0eeh
    db 011h
    db 0c4h
    db 03bh
    db 0c0h
    db 03fh
    db 0e0h
    db 000h
    db 0e0h
    db 00fh
    db 0e0h
    db 00fh
    db 0e0h
    db 017h
    db 0e0h
    db 018h
    db 0c0h
    db 020h
    db 080h
    db 050h
    db 000h
    db 0b0h
    db 000h
    db 0b8h
    db 000h
    db 0bch
    db 000h
    db 0beh
    db 080h
    db 04fh
    db 0c0h
    db 02fh
    db 0c0h
    db 02fh
    db 0c0h
    db 02fh
    db 0c0h
    db 02fh
    db 0c0h
    db 02fh
    db 0c0h
    db 02fh
    db 0c0h
    db 02fh
    db 0e0h
    db 010h
    db 0f0h
    db 00fh
    db 0ffh
__graphic01:
    db 01dh
    db 077h
    db 088h
    db 023h
    db 0dch
    db 003h
    db 0fch
    db 007h
    db 000h
    db 007h
    db 0f0h
    db 007h
    db 0f0h
    db 007h
    db 0e8h
    db 007h
    db 018h
    db 003h
    db 004h
    db 001h
    db 00ah
    db 000h
    db 00dh
    db 000h
    db 01dh
    db 000h
    db 03dh
    db 000h
    db 07dh
    db 001h
    db 0f2h
    db 003h
    db 0f4h
    db 003h
    db 0f4h
    db 003h
    db 0f4h
    db 003h
    db 0f4h
    db 003h
    db 0f4h
    db 003h
    db 0f4h
    db 003h
    db 0f4h
    db 007h
    db 008h
    db 00fh
    db 0f0h
    db 0ffh
;        ...XX.XX
;        ...XXXXX
;        ....    
;        .... XXX
;        ....X XX
;        ....XX  
;        ..XX    
;        ..X X   
;        .. XXX  
;        .. XXXX 
;        ..X  XXX
;        ...X XXX
;        ...X XXX
;        ...X XXX
;        ...X XXX
;        ...X XXX
;        ....X   
;        .....XXX
__graphic02:
    db 034h
    db 0e4h
    db 01bh
    db 0e0h
    db 01fh
    db 0f0h
    db 000h
    db 0f0h
    db 007h
    db 0f0h
    db 00bh
    db 0f0h
    db 00ch
    db 0c0h
    db 030h
    db 0c0h
    db 028h
    db 0c0h
    db 01ch
    db 0c0h
    db 01eh
    db 0c0h
    db 027h
    db 0e0h
    db 017h
    db 0e0h
    db 017h
    db 0e0h
    db 017h
    db 0e0h
    db 017h
    db 0e0h
    db 017h
    db 0f0h
    db 008h
    db 0f8h
    db 007h
    db 0ffh
__graphic03:
    db 035h
    db 027h
    db 0d8h
    db 007h
    db 0f8h
    db 00fh
    db 000h
    db 00fh
    db 0e0h
    db 00fh
    db 0d0h
    db 00fh
    db 030h
    db 003h
    db 00ch
    db 003h
    db 014h
    db 003h
    db 038h
    db 003h
    db 078h
    db 003h
    db 0e4h
    db 007h
    db 0e8h
    db 007h
    db 0e8h
    db 007h
    db 0e8h
    db 007h
    db 0e8h
    db 007h
    db 0e8h
    db 00fh
    db 010h
    db 01fh
    db 0e0h
    db 0ffh
;        ....X..X
;        ....    
;        .... XXX
;        ....X   
;        ...X    
;        ..X XX  
;        ..X XXX 
;        ..X  XXX
;        ...X XXX
;        ...X XXX
;        ...X XXX
;        ...X XXX
;        ....X   
;        .....XXX
__graphic04:
    db 044h
    db 0f6h
    db 009h
    db 0f0h
    db 000h
    db 0f0h
    db 007h
    db 0f0h
    db 008h
    db 0e0h
    db 010h
    db 0c0h
    db 02ch
    db 0c0h
    db 02eh
    db 0c0h
    db 027h
    db 0e0h
    db 017h
    db 0e0h
    db 017h
    db 0e0h
    db 017h
    db 0e0h
    db 017h
    db 0f0h
    db 008h
    db 0f8h
    db 007h
    db 0ffh
__graphic05:
    db 045h
    db 06fh
    db 090h
    db 00fh
    db 000h
    db 00fh
    db 0e0h
    db 00fh
    db 010h
    db 007h
    db 008h
    db 003h
    db 034h
    db 003h
    db 074h
    db 003h
    db 0e4h
    db 007h
    db 0e8h
    db 007h
    db 0e8h
    db 007h
    db 0e8h
    db 007h
    db 0e8h
    db 00fh
    db 010h
    db 01fh
    db 0e0h
    db 0ffh
;        .....X.X
;        .....   
;        ....X XX
;        .....X X
;        .....X  
;        ....X X 
;        ....X XX
;        ....X XX
;        .....X  
;        ......XX
__graphic06:
    db 054h
    db 0fah
    db 005h
    db 0f8h
    db 000h
    db 0f0h
    db 00bh
    db 0f8h
    db 005h
    db 0f8h
    db 004h
    db 0f0h
    db 00ah
    db 0f0h
    db 00bh
    db 0f0h
    db 00bh
    db 0f8h
    db 004h
    db 0fch
    db 003h
    db 0ffh
__graphic07:
    db 055h
    db 05fh
    db 0a0h
    db 01fh
    db 000h
    db 00fh
    db 0d0h
    db 01fh
    db 0a0h
    db 01fh
    db 020h
    db 00fh
    db 050h
    db 00fh
    db 0d0h
    db 00fh
    db 0d0h
    db 01fh
    db 020h
    db 03fh
    db 0c0h
    db 0ffh
;        ....XXX.
;        ...X   X
;        ..X     
;        ..X     
;        ..X     
;        ...X    
;        ....X   
;        .....X  
;        ......X 
;        .......X
__graphic08:
    db 0ach
    db 0f1h
    db 00eh
    db 0e0h
    db 011h
    db 0c0h
    db 020h
    db 0c0h
    db 020h
    db 0c0h
    db 020h
    db 0e0h
    db 010h
    db 0f0h
    db 008h
    db 0f8h
    db 004h
    db 0fch
    db 002h
    db 0feh
    db 001h
    db 0ffh
__graphic09:
    db 0adh
    db 08fh
    db 070h
    db 007h
    db 088h
    db 003h
    db 004h
    db 003h
    db 004h
    db 003h
    db 004h
    db 007h
    db 008h
    db 00fh
    db 010h
    db 01fh
    db 020h
    db 03fh
    db 040h
    db 07fh
    db 080h
    db 0ffh
;        .....XX.
;        ....X  X
;        ...X    
;        ...X    
;        ....X   
;        .....X  
;        ......X 
;        .......X
__graphic10:
    db 0b4h
    db 0f9h
    db 006h
    db 0f0h
    db 009h
    db 0e0h
    db 010h
    db 0e0h
    db 010h
    db 0f0h
    db 008h
    db 0f8h
    db 004h
    db 0fch
    db 002h
    db 0feh
    db 001h
    db 0ffh
__graphic11:
    db 0b5h
    db 09fh
    db 060h
    db 00fh
    db 090h
    db 007h
    db 008h
    db 007h
    db 008h
    db 00fh
    db 010h
    db 01fh
    db 020h
    db 03fh
    db 040h
    db 07fh
    db 080h
    db 0ffh
;        .....X X
;        ....X   
;        ....X   
;        .....X  
;        ......X 
;        .......X
__graphic12:
    db 0bch
    db 0f8h
    db 005h
    db 0f0h
    db 008h
    db 0f0h
    db 008h
    db 0f8h
    db 004h
    db 0fch
    db 002h
    db 0feh
    db 001h
    db 0ffh
__graphic13:
    db 0bdh
    db 01fh
    db 0a0h
    db 00fh
    db 010h
    db 00fh
    db 010h
    db 01fh
    db 020h
    db 03fh
    db 040h
    db 07fh
    db 080h
    db 0ffh
;        ......X.
;        .....X X
;        ......X 
;        .......X
__graphic14:
    db 0c4h
    db 0fdh
    db 002h
    db 0f8h
    db 005h
    db 0fch
    db 002h
    db 0feh
    db 001h
    db 0ffh
__graphic15:
    db 0c5h
    db 0bfh
    db 040h
    db 01fh
    db 0a0h
    db 03fh
    db 040h
    db 07fh
    db 080h
    db 0ffh
; 408
